#!/bin/sh

# Function to run a command and check its exit status
run_command() {
    echo -e "\033[0;33mRunning $1\033[0m"
    result=$($1)
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo -e "$result \n"
        echo -e "\033[0;31m$1 found issues, please fix them before pushing\033[0m"
        exit 1
    fi

    echo "$result"
    echo -e "\033[0;32mFinished running $1 with 0 issues\033[0m"
}

# Run dart analyze
run_command "dart analyze"

# Run flutter analyze
run_command "flutter analyze"

echo -e "\033[0;32mAll checks passed. Pushing changes.\033[0m"
exit 0